config/routes.rb
Govhack::Application.routes.draw do

  

  scope "(:locale)", :locale => /en|zh|hi/ do
    root :to => 'pages#home'
    get 'about' => 'pages#about', as: :about
    get 'contact' => 'pages#contact', as: :contact
    get 'university/:university_permalink' => 'pages#university', as: :university
    get 'university/:university_permalink/suburb/:suburb_permalink' => 'pages#suburb', as: :suburb
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  

  before_filter :set_locale
 
  private
  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
    Rails.application.routes.default_url_options[:locale]= I18n.locale
  end

end

app/controllers/pages_controller.rb
require 'json'

class PagesController < ApplicationController

  def about
  end

  def contact
  end

  def home
    json_data = File.read("#{ Rails.root }/db/data/universities.json")
    @universities = JSON.parse(json_data)
  end

  def university
    json_data = File.read("#{ Rails.root }/db/data/universities/#{ params[:university_permalink] }.json")

    @university = JSON.parse(json_data)
  end

  def suburb
    json_data = File.read("#{ Rails.root }/db/data/universities/#{ params[:university_permalink] }.json")

    @university = JSON.parse(json_data)
    @suburb_data = File.read("#{ Rails.root }/db/data/suburbs/#{ params[:suburb_permalink] }.json")

    @suburb = JSON.parse(@suburb_data)

    crime_data = File.read("#{ Rails.root }/db/data/crime/sydney.json")
    @crime = JSON.parse(crime_data)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def distance_between(lat1, long1, lat2, long2)
    Geocoder::Calculations.distance_between([lat1, long1], [lat2, long2])
  end
end

app/views/layouts/application.html.haml
!!! Strict
%html{ :lang => "en" }
  %head
    %meta{ :charset => "utf-8" }
    %title= "#{ yield :title }"

    %link{ :rel => "shortcut icon", :href => "#{ asset_path('favicon.ico') }" }
    %link{ :href => 'http://fonts.googleapis.com/css?family=Roboto', :rel=>'stylesheet', :type=>'text/css'}
    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0 initial-scale=1, maximum-scale=1" }

    = stylesheet_link_tag "frontend",:media => "all"

    = yield :css_header

    = javascript_include_tag "frontend.js"
    = yield :js_header
    = csrf_meta_tag
    %link{ :href => 'http://fonts.googleapis.com/css?family=Lato:100', :rel=>'stylesheet', :type=>'text/css'}

  %body
    #content
      = render :partial => "shared/header"      
      .container-fluid
        .breadcrumbs
          = yield :breadcrumbs
        = yield
      = render :partial => "shared/footer"
    = yield :js_footer

app/views/pages/_description.html.haml
%section#description.widgit
  %p= @suburb["description_#{ I18n.locale }"]
  %p= @suburb["history_#{ I18n.locale }"]

app/views/pages/about.html.haml
%h1 About

app/views/pages/home.html.haml
.container-fluid
  .row-fluid
    %section#universities.span12
      - @universities["universities"].each do |university|
        %div{ :class => "university span6" }
          = link_to image_tag(university["logo"], :alt => university["name"], :title => university["name"]), university_path( :university_permalink => university["permalink"])
    

app/views/pages/suburb.html.haml
.container-fluid
  .row-fluid

    %ul{ :class => "breadcrumb" }
      %li
        = link_to t(:home), root_path
        %span{ :class => "divider" }
          = "/"
      %li
        = link_to @university["name"], university_path( :university_permalink => @university["permalink"], :suburb_permalink => @suburb["permalink"])
        %span{ :class => "divider" }
          = "/"
      %li{ :class => "active" }
        = link_to @suburb["name"], suburb_path(:university_permalink => @university["permalink"], :suburb_permalink => @suburb["permalink"])


    #suburb-show
      %h1
        = @suburb["name"]
      
      .span12
        = render :partial => "pages/suburbs/description"

      .row-fluid
        .span3
          = render :partial => "pages/suburbs/population"
        .span3
          = render :partial => "pages/suburbs/accomodation"

        .span3
          = render :partial => "pages/suburbs/work"
        .span3
          = render :partial => "pages/suburbs/modes_of_travel"
      .row-fluid
        .span3
          = render :partial => "pages/suburbs/crime"
        .span3
          = render :partial => "pages/suburbs/streetview"
        .span3
          = render :partial => "pages/suburbs/country"             
      .row-fluid
        .span12
          = render :partial => "pages/suburbs/photos_of_the_area"          
      .row-fluid
        .span12
          = render :partial => "pages/suburbs/map"                  

app/views/pages/suburbs/_accomodation.html.haml
%section#accomodation.widgit.white
  %h2= t(:accomodation)
  
  %p
    %span
      %strong= "#{ t(:average_mortage) }: "
      %br
      = "$#{ @suburb["economy"]["averageMortage"] }"
      = t(:per_month)

      - if @suburb["economy"]["averageMortage"] > 2185
        = image_tag "red_up.png", :size => "25x25", :alt => "NSW mortage average: $1442", :title => "NSW mortage average: $1442"
      - else
        = image_tag "green_down.png", :size => "25x25", :alt => "NSW mortage average: $1442", :title => "NSW mortage average: $1442"
        
    %br
    %span
      %strong= "#{ t(:average_rental) }: "
      %br
      = "$#{ @suburb["economy"]["averageRental"] }"
      = t(:per_month)
      - if @suburb["economy"]["averageRental"] > 1442
        = image_tag "red_up.png", :size => "25x25", :alt => "NSW rental average: $1442",  :title => "NSW rental average: $1442"
      - else
        = image_tag "green_down.png", :size => "25x25", :alt => "NSW rental average: $1442", :title => "NSW rental average: $1442"

      

app/views/pages/suburbs/_country.html.haml
%section#photos.widgit.white
  %h2
    = t(:country)
   
  - @suburb["summary"]["ethnicity"].each do |a|
    %p
      %span
        = "#{ a["value"] }%:"
      %strong
        = "#{ a["key"] }:"

app/views/pages/suburbs/_country_breakdown.html.erb
<%= content_for(:js_header) do %>
  <%= javascript_include_tag "http://d3js.org/d3.v2.js" %>
<% end %>
<script type="text/javascript">

//////////// READY ///////////
jQuery(document).ready(function() {
var a = "<%= @suburb["summary"]["ethnicity"] %>";
var decoded = jQuery("<div/>").html(a).text();

doBornPieChart(decoded);
});
/////////////////////////////

function doBornPieChart(dataObj) {

	// This is an array.
	ethBreak = JSON.parse(dataObj);
	
	var w = 300, //width
	h = 200, //height
	r = 100, //radius
	color = d3.scale.category20c(); //builtin range of colors
	
	data = ethBreak;
	
	var vis = d3.select("div#chartHere")
	.append("svg:svg") //create the SVG element inside the <body>
	.data([data]) //associate our data with the document
	.attr("width", w) //set the width and height of our visualization (these will be attributes of the <svg> tag
	.attr("height", h)
	.append("svg:g") //make a group to hold our pie chart
	.attr("transform", "translate(" + r + "," + r + ")") //move the center of the pie chart from 0, 0 to radius, radius
	 
	var arc = d3.svg.arc() //this will create <path> elements for us using arc data
	.outerRadius(r);
	 
	var pie = d3.layout.pie() //this will create arc data for us given a list of values
	.value(function(d) { return d.value; }); //we must tell it out to access the value of each element in our data array
	 
	var arcs = vis.selectAll("g.slice") //this selects all <g> elements with class slice (there aren't any yet)
	.data(pie) //associate the generated pie data (an array of arcs, each having startAngle, endAngle and value properties)
	.enter() //this will create <g> elements for every "extra" data element that should be associated with a selection. The result is creating a <g> for every object in the data array
	.append("svg:g") //create a group to hold each slice (we will have a <path> and a <text> element associated with each slice)
	.attr("class", "slice"); //allow us to style things in the slices (like text)
	 
	var dataColour = [];
	
	arcs.append("svg:path")
	.attr("fill", function(d, i) {
		var c = color(i);
		dataColour.push(c);
		return c;
	} ) //set the color for each slice to be chosen from the color function defined above
	.attr("d", arc); //this creates the actual SVG path using the associated data (pie) with the arc drawing function

	for (var i = 0; i < data.length; ++i) {
		var d = data[i];
		var c = dataColour[i];
		jQuery("#legendHere").append(
			'<tr><td bgcolor="' + c + '">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>' + d.key + '</td></tr>'
			);
	}
	
	/*
	arcs.append("svg:text") //add a label to each slice
	.attr("transform", function(d) { //set the label's origin to the center of the arc
	//we have to make sure to set these before calling arc.centroid
	d.innerRadius = 0;
	d.outerRadius = r;
	return "translate(" + arc.centroid(d) + ")"; //this gives us a pair of coordinates like [50, 50]
	})
	.attr("text-anchor", "middle") //center the text on it's origin
	.text(function(d, i) {
		var p = data[i].key;
		alert(p);
		return p; }); //get the label from our original data array
		*/
}

</script>

<H2>chart</h2>
<div id="chartHere"></div>
<div>
<table id="legendHere">
</table>

app/views/pages/suburbs/_crime.html.haml
%section#photos.widgit.white
  %h2
    = t(:crime)
    (2008) - Sydney
  %p
    = "#{ t(:motor_vehicle_theft) } :"
    = @crime["steal_from_motor_vehicle"]
    = image_tag "green_down.png", :size => "25x25"
  %p
    = "#{ t(:mugging) }:"
    = @crime["steal_from_person"]
    = image_tag "green_down.png", :size => "25x25"
  %p
    = "#{ t(:fraud) }:"
    = @crime["fraud"]
    = image_tag "red_up.png", :size => "25x25"
  %p
    = "#{ t(:damage_to_property) }:"
    = @crime["malicious_damage_to_property"]
    = image_tag "green_down.png", :size => "25x25"

app/views/pages/suburbs/_ethnicity.html.haml
%section#travel.widgit.white
  %h2= t(:ethnic_background)
  %ul
    %li
      = @suburb["summary"]["ethnicity"]

app/views/pages/suburbs/_map.html.erb
<%= content_for(:js_header) do %>
<script charset="UTF-8" type="text/javascript" src="https://ecn.dev.virtualearth.net/mapcontrol/mapcontrol.ashx?v=7.0&s=1">
</script>
<script type="text/javascript">

function DoTrends(lat, longi, name) {
	// dataObj is the trends data loaded as JSON object.
	var map = GetMap();
	pageVarMap = map; // Saved for later, when adding infoboxes.

	var loc = new Microsoft.Maps.Location(lat, longi);

	// Create pushpin and add to map.
	var infoboxOptions = {
		title: name,
		height: 45
	};
	var infobox = new Microsoft.Maps.Infobox(loc, infoboxOptions);
	map.entities.push(infobox);

	// Adjust map centre.
	map.setView({center: loc, zoom: 15});
}

function GetMap() {
	var map = new Microsoft.Maps.Map(document.getElementById("mapDiv"), {credentials:"AqcVomk22ni48gUWhOLwbPRBv9_dIRLJ1RxciambLPCGToDAsmiqB_DGhyzBeDYE"});
	map.entities.clear();
	return map;
}

//////////// READY ///////////
jQuery(document).ready(function() {
	// CHANGE HERE, lat, long, suburb.
	DoTrends(<%= @suburb["latitude"] %>, <%= @suburb["longitude"] %>, "<%= @suburb["name"] %>");
});

</script>


<% end %>

<div id='mapDiv' style="position:relative; width:850px; height:200px; width:100%;"></div>

app/views/pages/suburbs/_modes_of_travel.html.haml
%section#travel.widgit.white
  %h2= t(:modes_of_transport)
  %ul
    - (0..@suburb["summary"]["travel_car"].to_i ).each do |i|
      %li= image_tag "travel/car.png", :size => "20x20"
  %ul
    - (0..@suburb["summary"]["travel_bus"].to_i ).each do |i|
      %li= image_tag "travel/bus.png", :size => "20x20"
  %ul
    - (0..@suburb["summary"]["travel_moto"].to_i ).each do |i|
      %li= image_tag "travel/motorcycle.png", :size => "20x20"
  %ul
    - (0..@suburb["summary"]["travel_tram"].to_i ).each do |i|
      %li= image_tag "travel/tram.png", :size => "20x20"
  %ul
    - (0..@suburb["summary"]["travel_walk"].to_i ).each do |i|
      %li= image_tag "travel/walk.png", :size => "20x20"
  %ul
    - (0..@suburb["summary"]["travel_bicycle"].to_i ).each do |i|
      %li= image_tag "travel/bicycle.png", :size => "20x20"

app/views/pages/suburbs/_photos_of_the_area.html.haml
%section#photos.widgit.white
  %h2= t(:photos_of_the_area)
  - @suburb["photos"].each do |photo|
    %a{ :href => photo["url"], :rel=>"lightbox[suburb]", :alt => photo["title_en"], :title => photo["title_en"] }
      = image_tag photo["thumbUrl"], :size => "64x64", :alt => photo["title_en"], :title => photo["title_en"]
      

app/views/pages/suburbs/_population.html.haml
%section#population.widgit.white
  %h2= t(:population)
  %p
    - (0...@suburb["summary"]["female"].to_i).each do |i|
      = image_tag "female.png", :size => "20x20"
  %p      
    - (0...@suburb["summary"]["male"].to_i).each do |i|
      = image_tag "male.png", :size => "20x20"

app/views/pages/suburbs/_streetview.html.haml
%section#photos.widgit.white
  %h2= t(:streetview)
  %a{ :href => "http://maps.googleapis.com/maps/api/streetview?size=800x800&location=#{ @suburb["name"]}&heading=235&sensor=false", :alt => @suburb["name"], :title => @suburb["name"], :rel=>"lightbox[suburb]" }
    %img{ :src=>"http://maps.googleapis.com/maps/api/streetview?size=200x200&location=#{ @suburb["name"]}&heading=235&sensor=false"}
 

app/views/pages/suburbs/_work.html.haml
%section#work.widgit.white
  %h2= t(:work)
  %p
    %span= t(:part_time_work_student)
    = "#{ @suburb["economy"]["youthWorkPartStudyFull"] }%"
  %p
    %span
      = "#{ t(:unemployment_rate) }: "
    = "#{ @suburb["economy"]["unemplymentRate"] }%"

app/views/pages/university.html.haml
.container-fluid
  .row-fluid
    .span12
      .span5
        = image_tag(@university["logo"], :alt =>  @university["name"])
      .span1
      .span6
        %div{ :id => "university-meta" }
          %section#address
            = @university["address"]
            %i{ :class=>"icon-globe" }
          
          %section#phone
            %a{ :href => "tel:#{ @university["phone"] }" }
              = @university["phone"]
            %i{ :class=>"icon-envelope" }
            
  .row-fluid
    .span12
      %section{ :id => "surrounding_suburbs" }
        %h2= t(:suburbs).capitalize
        %ul
          - @university["suburbs"].each do |suburb|
            %li
              %a{ :href => suburb_path(:university_permalink => @university["permalink"], :suburb_permalink => suburb["permalink"]), :class => "suburb span12 #{ cycle("even", "odd") }" }
                = suburb["name"]

app/views/shared/_footer.html.haml
%footer
  %section#locales
    %ul
      - unless I18n.locale == :en
        %li
          = link_to image_tag("flags/en.png", :alt => t(:switch_english_language), :title => t(:switch_english_language)), locale: :en
      - unless I18n.locale == :zh
        %li
          = link_to image_tag("flags/zh.png", :alt => t(:switch_mandarin_language), :title => t(:switch_mandarin_language)), locale: :zh
      - unless I18n.locale == :hi
        %li
          = link_to image_tag("flags/hi.png", :alt => t(:switch_hindi_language), :title => t(:switch_hindi_language)), locale: :hi

          
  
  

app/views/shared/_header.html.haml
%header
  %h1
    = link_to "UniBurb!", root_path
  